### ISSUE TITLE
Keywords should be split when separated by semicolons

### ISSUE THREAD

**Issue by ylyangtw** [earthcube/hydrography.org#19]
Some datasets' keywords are not separated properly, need to add a condition to handle them.
Here is one example:
https://geochemistry.geocodes-aws.earthcube.org/#/dataset/urn:gleaner.io:eco:geochemistry_custom:data:2cdf5fb9468dc5ffacb9ca9d7fcd5b7d3f0a04f8
![image](https://github.com/user-attachments/assets/26418b49-96d6-436b-a361-4527f909f4e7)

**Comment by valentinedwv** [comment]
https://github.com/earthcube/earthcube_utilities/issues/183

**Comment by ylyangtw** [comment]
close as it's done
