### ISSUE TITLE
Steps to prep for hydrography.org

### ISSUE THREAD

**Issue by valentinedwv** [earthcube/hydrography.org#2]
Suggested steps.

1. Merge decoder branchinto earth cube/hydrography.org/main branch
2. edit print-json-ld.js baseUrl to point at hydrography.org
3. run rint-json-ld.js
4. commit changes 
5. create PR for hydrography.org/main branch.. wait did we not fork from the original repo... get it to them...

**Comment by ylyangtw** [comment]
close as it's done
