### ISSUE TITLE
Update JSON LD for tiles

### ISSUE THREAD

**Issue by valentinedwv** [earthcube/hydrography.org#3]
print-json-ld.js generates the JSONLD

This needs to have the appropriate keywords, variables, etc. Suspect it's a grab bag captured from a jinja2 python project.

- title: appropriate title (datasets for hydrography org tile hxxvxx, lat long)
-  description (work with hydorgraphy.org ("this is a tile containing like to datasets for (location), this includes (basic names like elevation, discharge, etc)
- org correct
- contact correct
- date published, etc
- add keywords, if appropriate
- update variableMeasures see if we cannot capture appropriate variables to be for each dataset in tile. maybe do this as a csv so we can use them when generating the layer jsonLD
- add appropriate name to distributions.

# ADD SPATIAL
each tile has a spatial component. Figure out what it is, and use it to generate the spatial. 

# drop temporal, unless it's needed

**Comment by ylyangtw** [comment]
close as it's done
