### ISSUE TITLE
Add JSONLD for each of the layers

### ISSUE THREAD

**Issue by valentinedwv** [earthcube/hydrography.org#4]
I put a couple of skeletons in hydrography90m_layers.md. 

* [jsonld script](https://github.com/earthcube/hydrography.org/blob/3241a06adfc59a040b811df75600f823601b564e/pages/hydrography90m/hydrography90m_layers.md?plain=1#L587)
* [jsonld script](https://github.com/earthcube/hydrography.org/blob/3241a06adfc59a040b811df75600f823601b564e/pages/hydrography90m/hydrography90m_layers.md?plain=1#L817)

For each layer we should link to just the _dataset directory or website_, and **not the individual distributions**. as is done in the tiles jsonld.

* two links
https://github.com/earthcube/hydrography.org/blob/3241a06adfc59a040b811df75600f823601b564e/pages/hydrography90m/hydrography90m_layers.md?plain=1#L922-L923

* one link https://github.com/earthcube/hydrography.org/blob/3241a06adfc59a040b811df75600f823601b564e/pages/hydrography90m/hydrography90m_layers.md?plain=1#L689

**Comment by ylyangtw** [comment]
close as it's done
